"""
Dynamically generates Terraform HCL configuration based on user input.
"""

# Latest AMI IDs by region (update periodically)
AMI_MAP = {
    "amazon_linux": {
        "us-east-1":      "ami-0c02fb55956c7d316",
        "us-east-2":      "ami-0ba62214afa52bec7",
        "us-west-1":      "ami-07dd191a0929cd25c",
        "us-west-2":      "ami-00ee4df451840fa9d",
        "ap-south-1":     "ami-08df646e18b182346",
        "ap-southeast-1": "ami-0f62d9254ca98e1aa",
        "ap-northeast-1": "ami-0f9ae750e8274075b",
        "eu-west-1":      "ami-04dd4500af104442f",
        "eu-central-1":   "ami-06616b7884ac98cdd",
        "ca-central-1":   "ami-04a79d8d7cfa540cc",
    },
    "ubuntu": {
        "us-east-1":      "ami-0557a15b87f6559cf",
        "us-east-2":      "ami-024e6efaf93d85776",
        "us-west-1":      "ami-0d50e5e845c552faf",
        "us-west-2":      "ami-0735c191cf914754d",
        "ap-south-1":     "ami-0287a05f0ef0e9d9a",
        "ap-southeast-1": "ami-062550af7b9fa7d05",
        "ap-northeast-1": "ami-0d52744d6551d851e",
        "eu-west-1":      "ami-0694d931cee176e7d",
        "eu-central-1":   "ami-0faab6bdbac9486fb",
        "ca-central-1":   "ami-0a7154091c5c6623e",
    },
}

DEFAULT_AMI = "ami-0c02fb55956c7d316"


def generate_terraform(request) -> str:
    os_key = request.os_type if request.os_type in AMI_MAP else "amazon_linux"
    region_amis = AMI_MAP.get(os_key, AMI_MAP["amazon_linux"])
    ami = region_amis.get(request.region, DEFAULT_AMI)

    # Build ingress rules
    ports = list(set(request.security_group_ports))
    if 22 not in ports:
        ports.insert(0, 22)  # Always allow SSH

    ingress_blocks = ""
    for port in ports:
        ingress_blocks += f"""
  ingress {{
    description = "Port {port}"
    from_port   = {port}
    to_port     = {port}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}"""

    tf = f"""# ============================================================
# Generated by DevOps Automation Portal
# Provider : {request.provider.upper()}
# Region   : {request.region}
# OS       : {request.os_type}
# ============================================================

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{request.region}"
  # Credentials are read from AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY env vars
}}

# ---------- Security Group ----------
resource "aws_security_group" "devops_portal_sg" {{
  # Use a prefix so repeated deployments do not fail on duplicate SG names.
  name_prefix = "devops-portal-sg-"
  description = "Managed by DevOps Automation Portal"
{ingress_blocks}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Name      = "devops-portal-sg"
    ManagedBy = "DevOpsAutomationPortal"
  }}
}}

# ---------- EC2 Instances ----------
resource "aws_instance" "devops_portal_server" {{
  count         = {request.instances}
  ami           = "{ami}"   # {request.os_type} in {request.region}
  instance_type = "{request.instance_type}"
  key_name      = "{request.key_pair_name}"

  vpc_security_group_ids = [aws_security_group.devops_portal_sg.id]

  root_block_device {{
    volume_size = 20
    volume_type = "gp3"
    encrypted   = true
  }}

  tags = {{
    Name        = "devops-portal-server-${{count.index + 1}}"
    Environment = "devops-portal"
    ManagedBy   = "DevOpsAutomationPortal"
  }}
}}

# ---------- Outputs ----------
output "instance_public_ips" {{
  description = "Public IP addresses of created instances"
  value       = aws_instance.devops_portal_server[*].public_ip
}}

output "instance_ids" {{
  description = "Instance IDs"
  value       = aws_instance.devops_portal_server[*].id
}}

output "security_group_id" {{
  description = "Security Group ID"
  value       = aws_security_group.devops_portal_sg.id
}}
"""
    return tf
